let iconsPath = {
    //
    "dps":"img/roles/role_dps.png",
    "healer":"img/roles/role_healer.png",
    "tank":"img/roles/role_tank.png",
    //specs
    specs: {
        "mistweaver":"img/specs/monk/mistweaver.png",
        "windwalker":"img/specs/monk/windwalker.png",
        "brewmaster":"img/specs/monk/brewmaster.png",
        "restorationShaman":"img/specs/shaman/restoration.png",
        "elemental":"img/specs/shaman/elemental.png",
        "assassination":"img/specs/rogue/assassination.png",
        "restorationDruid":"img/specs/druid/restoration.png",
        "balance":"img/specs/druid/balance.png",
        "arcane":"img/specs/mage/arcane.png",
        "havoc":"img/specs/demonhunter/havoc.jpg",
    },

    //classes
    classes: {
        "Death Knight":"img/classes/deathknight.png",
        "Demon Hunter":"img/classes/demonhunter.jpg",
        "Druid":"img/classes/druid.png",
        "Hunter":"img/classes/hunter.png",
        "Mage":"img/classes/mage.png",
        "Monk":"img/classes/monk.png",
        "Paladin":"img/classes/paladin.png",
        "Priest":"img/classes/priest.png",
        "Rogue":"img/classes/rogue.png",
        "Shaman":"img/classes/shaman.png",
        "Warlock":"img/classes/warlock.png",
        "Warrior":"img/classes/warrior.png",
    },

    "Mana Potion":"img/ManaPotion.jpg",
    "Auto Attack":"img/AutoAttack.jpg",
    "Leech":"img/Leech.jpg",

    //Death Knight
    "All Will Serve":"img/deathKnight/AllWillServe.jpg",
    "Blooddrinker":"img/deathKnight/Blooddrinker.jpg",
    "Breath of Sindragosa":"img/deathKnight/BreathofSindragosa.jpg",
    "Frostscythe":"img/deathKnight/Frostscythe.jpg",
    "Gathering Storm":"img/deathKnight/GatheringStorm.jpg",
    "Glacial Advance":"img/deathKnight/GlacialAdvance.jpg",
    "Horn of Winter":"img/deathKnight/HornofWinter.jpg",
    "Inexorable Assault":"img/deathKnight/InexorableAssault.jpg",
    "Pestilence":"img/deathKnight/Pestilence.jpg",
    "Purgatory":"img/deathKnight/Purgatory.jpg",
    "Rapid Decomposition":"img/deathKnight/RapidDecomposition.jpg",
    "Soul Reaper":"img/deathKnight/SoulReaper.jpg",
    "Summon Gargoyle":"img/deathKnight/SummonGargoyle.jpg",
    "Wraith Walk":"img/deathKnight/WraithWalk.jpg",
    "Anti-Magic Barrier":"img/deathKnight/Anti-MagicBarrier.jpg",
    "Army of the Damned":"img/deathKnight/ArmyoftheDamned.jpg",
    "Asphyxiate":"img/deathKnight/Asphyxiate.jpg",
    "Avalanche":"img/deathKnight/Avalanche.jpg",
    "Blinding Sleet":"img/deathKnight/BlindingSleet.jpg",
    "Blood Tap":"img/deathKnight/BloodTap.jpg",
    "Bloodworms":"img/deathKnight/Bloodworms.jpg",
    "Bonestorm":"img/deathKnight/Bonestorm.jpg",
    "Bursting Sores":"img/deathKnight/BurstingSores.jpg",
    "Clawing Shadows":"img/deathKnight/ClawingShadows.jpg",
    "Cold Heart":"img/deathKnight/ColdHeart.jpg",
    "Consumption":"img/deathKnight/Consumption.jpg",
    "Death Pact":"img/deathKnight/DeathPact.jpg",
    "Death's Reach":"img/deathKnight/DeathsReach.jpg",
    "Defile":"img/deathKnight/Defile.jpg",
    "Ebon Fever":"img/deathKnight/EbonFever.jpg",
    "Foul Bulwark":"img/deathKnight/FoulBulwark.jpg",
    "Frozen Pulse":"img/deathKnight/FrozenPulse.jpg",
    "Grip of the Dead":"img/deathKnight/GripoftheDead.jpg",
    "Harbinger of Doom":"img/deathKnight/HarbingerofDoom.jpg",
    "Heartbreaker":"img/deathKnight/Heartbreaker.jpg",
    "Hemostasis":"img/deathKnight/Hemostasis.jpg",
    "Hypothermic Presence":"img/deathKnight/HypothermicPresence.jpg",
    "Icecap":"img/deathKnight/Icecap.jpg",
    "Icy Talons":"img/deathKnight/IcyTalons.jpg",
    "Infected Claws":"img/deathKnight/InfectedClaws.jpg",
    "Mark of Blood":"img/deathKnight/MarkofBlood.jpg",
    "Murderous Efficiency":"img/deathKnight/MurderousEfficiency.jpg",
    "Obliteration":"img/deathKnight/Obliteration.jpg",
    "Permafrost":"img/deathKnight/Permafrost.jpg",
    "Pestilent Pustules":"img/deathKnight/PestilentPustules.jpg",
    "Red Thirst":"img/deathKnight/RedThirst.jpg",
    "Relishin Blood":"img/deathKnight/RelishinBlood.jpg",
    "Spell Eater":"img/deathKnight/SpellEater.jpg",
    "Tightening Grasp":"img/deathKnight/TighteningGrasp.jpg",
    "Tombstone":"img/deathKnight/Tombstone.jpg",
    "Unholy Assault":"img/deathKnight/UnholyAssault.jpg",
    "Unholy Blight":"img/deathKnight/UnholyBlight.jpg",
    "Unholy Pact":"img/deathKnight/UnholyPact.jpg",
    "Voracious":"img/deathKnight/Voracious.jpg",
    "Anti-Magic Shell":"img/deathKnight/Anti-MagicShell.jpg",
    "Anti-Magic Zone":"img/deathKnight/Anti-Magic Zone.jpg",
    "Apocalypse":"img/deathKnight/Apocalypse.jpg",
    "Army of the Dead":"img/deathKnight/ArmyoftheDead.jpg",
    "Blood Boil":"img/deathKnight/BloodBoil.jpg",
    "Blood Plague":"img/deathKnight/BloodPlague.jpg",
    "Blood Shield":"img/deathKnight/BloodShield.jpg",
    "Control Undead":"img/deathKnight/ControlUndead.jpg",
    "Corpse Exploder":"img/deathKnight/CorpseExploder.jpg",
    "Crimson Scourge":"img/deathKnight/CrimsonScourge.jpg",
    "Dancing Rune Weapon":"img/deathKnight/DancingRuneWeapon.jpg",
    "Dark Command":"img/deathKnight/DarkCommand.jpg",
    "Dark Succor":"img/deathKnight/DarkSuccor.jpg",
    "Dark Transformation":"img/deathKnight/DarkTransformation.jpg",
    "Death and Decay":"img/deathKnight/DeathandDecay.jpg",
    "Death Coil":"img/deathKnight/DeathCoil.jpg",
    "Death Grip":"img/deathKnight/DeathGrip.jpg",
    "Deaths Advance":"img/deathKnight/DeathsAdvance.jpg",
    "Deaths Caress":"img/deathKnight/DeathsCaress.jpg",
    "Death Strike":"img/deathKnight/DeathStrike.jpg",
    "Dreadblade":"img/deathKnight/Dreadblade.jpg",
    "Empower Rune Weapon":"img/deathKnight/EmpowerRuneWeapon.jpg",
    "Epidemic":"img/deathKnight/Epidemic.jpg",
    "Festering Strike":"img/deathKnight/FesteringStrike.jpg",
    "Festering Wound":"img/deathKnight/FesteringWound.jpg",
    "Frost Breath":"img/deathKnight/FrostBreath.jpg",
    "Frost Fever":"img/deathKnight/FrostFever.jpg",
    "Frost Strike":"img/deathKnight/FrostStrike.jpg",
    "Frostwyrm's Fury":"img/deathKnight/FrostwyrmsFury.jpg",
    "Frozen Heart":"img/deathKnight/FrozenHeart.jpg",
    "Gorefiends Grasp":"img/deathKnight/GorefiendsGrasp.jpg",
    "HeartS trike":"img/deathKnight/HeartStrike.jpg",
    "Howling Blast":"img/deathKnight/Howling Blast.jpg",
    "Chains of Ice":"img/deathKnight/ChainsofIce.jpg",
    "Icebound Fortitude":"img/deathKnight/IceboundFortitude.jpg",
    "Killing Machine":"img/deathKnight/KillingMachine.jpg",
    "Lichborne":"img/deathKnight/Lichborne.jpg",
    "Marrowrend":"img/deathKnight/Marrowrend.jpg",
    "Mind Freeze":"img/deathKnight/MindFreeze.jpg",
    "Obliterate":"img/deathKnight/Obliterate.jpg",
    "Ossuary":"img/deathKnight/Ossuary.jpg",
    "Outbreak":"img/deathKnight/Outbreak.jpg",
    "Path of Frost":"img/deathKnight/PathofFrost.jpg",
    "Pillar of Frost":"img/deathKnight/PillarofFrost.jpg",
    "Raise Ally":"img/deathKnight/RaiseAlly.jpg",
    "Raise Dead":"img/deathKnight/RaiseDead.jpg",
    "Remorseless Winter":"img/deathKnight/RemorselessWinter.jpg",
    "Rime":"img/deathKnight/Rime.jpg",
    "Rune Strike":"img/deathKnight/RuneStrike.jpg",
    "Rune Tap":"img/deathKnight/RuneTap.jpg",
    "Runic Corruption":"img/deathKnight/RunicCorruption.jpg",
    "Sacrificial Pact":"img/deathKnight/SacrificialPact.jpg",
    "Scourge Strike":"img/deathKnight/ScourgeStrike.jpg",
    "Sudden Doom":"img/deathKnight/SuddenDoom.jpg",
    "Vampiric Blood":"img/deathKnight/VampiricBlood.jpg",
    "Veteran of the Third War":"img/deathKnight/VeteranoftheThirdWar.jpg",

    //Demon Hunter
    "Chaos Brand":"img/demonHunter/ChaosBrand.jpg",
    "Annihilation":"img/demonHunter/Annihilation.jpg",
    "Blade Dance":"img/demonHunter/BladeDance.jpg",
    "Death Sweep":"img/demonHunter/DeathSweep.jpg",
    "Demon's Bite":"img/demonHunter/DemonsBite.jpg",
    "Eye Beam":"img/demonHunter/EyeBeam.jpg",
    "Chaos Strike":"img/demonHunter/ChaosStrike.jpg",
    "Immolation Aura":"img/demonHunter/ImmolationAura.jpg",
    "Metamorphosis":"img/demonHunter/Metamorphosis.jpg",
    "Abyssal Strike":"img/demonHunter/AbyssalStrike.jpg",
    "Agonizing Flames":"img/demonHunter/AgonizingFlames.jpg",
    "Blind Fury":"img/demonHunter/BlindFury.jpg",
    "Blur":"img/demonHunter/Blur.jpg",
    "Bulk Extraction":"img/demonHunter/BulkExtraction.jpg",
    "Burning Alive":"img/demonHunter/BurningAlive.jpg",
    "Burning Hatred":"img/demonHunter/BurningHatred.jpg",
    "Concentrated Sigils":"img/demonHunter/ConcentratedSigils.jpg",
    "Consume Magic":"img/demonHunter/ConsumeMagic.jpg",
    "Cycle of Hatred":"img/demonHunter/CycleofHatred.jpg",
    "Darkness":"img/demonHunter/Darkness.jpg",
    "Demon Blades":"img/demonHunter/DemonBlades.jpg",
    "Demonic":"img/demonHunter/Demonic.jpg",
    "Demonic Appetite":"img/demonHunter/DemonicAppetite.jpg",
    "Demonic Presence":"img/demonHunter/DemonicPresence.jpg",
    "Demonic Wards":"img/demonHunter/DemonicWards.jpg",
    "Demon Spikes":"img/demonHunter/DemonSpikes.jpg",
    "Desperate Instincts":"img/demonHunter/DesperateInstincts.jpg",
    "Disrupt":"img/demonHunter/Disrupt.jpg",
    "Essence Break":"img/demonHunter/EssenceBreak.jpg",
    "Fallout":"img/demonHunter/Fallout.jpg",
    "Feast of Souls":"img/demonHunter/FeastofSouls.jpg",
    "Feed the Demon":"img/demonHunter/FeedtheDemon.jpg",
    "Fel Barrage":"img/demonHunter/FelBarrage.jpg",
    "Fel blade":"img/demonHunter/Felblade.jpg",
    "Fel Blood":"img/demonHunter/FelBlood.jpg",
    "Fel Devastation":"img/demonHunter/FelDevastation.jpg",
    "Fel Eruption":"img/demonHunter/FelEruption.jpg",
    "Fel Rush":"img/demonHunter/FelRush.jpg",
    "Fiery Brand":"img/demonHunter/FieryBrand.jpg",
    "First Blood":"img/demonHunter/FirstBlood.jpg",
    "Fracture":"img/demonHunter/Fracture.jpg",
    "Glaive Tempest":"img/demonHunter/GlaiveTempest.jpg",
    "Glide":"img/demonHunter/Glide.jpg",
    "Chaos Nova":"img/demonHunter/ChaosNova.jpg",
    "Charred Flesh":"img/demonHunter/CharredFlesh.jpg",
    "Imprison":"img/demonHunter/Imprison.jpg",
    "Infernal Armor":"img/demonHunter/InfernalArmor.jpg",
    "Infernal Strike":"img/demonHunter/InfernalStrike.jpg",
    "Insatiable Hunger":"img/demonHunter/InsatiableHunger.jpg",
    "Last Resort":"img/demonHunter/LastResort.jpg",
    "Master of the Glaive":"img/demonHunter/MasteroftheGlaive.jpg",
    "Momentum":"img/demonHunter/Momentum.jpg",
    "Netherwalk":"img/demonHunter/Netherwalk.jpg",
    "Quickened Sigils":"img/demonHunter/QuickenedSigils.jpg",
    "Revelin Pain":"img/demonHunter/RevelinPain.jpg",
    "Ruinous Bulwark":"img/demonHunter/RuinousBulwark.jpg",
    "Shattered Souls":"img/demonHunter/ShatteredSouls.jpg",
    "Shear":"img/demonHunter/Shear.jpg",
    "Sigil of Flame":"img/demonHunter/SigilofFlame.jpg",
    "Sigil of Chains":"img/demonHunter/SigilofChains.jpg",
    "Sigil of Misery":"img/demonHunter/SigilofMisery.jpg",
    "Sigil of Silence":"img/demonHunter/SigilofSilence.jpg",
    "Soul Barrier":"img/demonHunter/SoulBarrier.jpg",
    "Soul Carver":"img/demonHunter/SoulCarver.jpg",
    "Soul Cleave":"img/demonHunter/SoulCleave.jpg",
    "Soul Rending":"img/demonHunter/SoulRending.jpg",
    "Spectral Sight":"img/demonHunter/SpectralSight.jpg",
    "Spirit Bomb":"img/demonHunter/SpiritBomb.jpg",
    "Thick Skin":"img/demonHunter/ThickSkin.jpg",
    "Throw Glaive":"img/demonHunter/ThrowGlaive.jpg",
    "Torment":"img/demonHunter/Torment.jpg",
    "Trail of Ruin":"img/demonHunter/TrailofRuin.jpg",
    "Unbound Chaos":"img/demonHunter/UnboundChaos.jpg",
    "Unleashed Power":"img/demonHunter/UnleashedPower.jpg",
    "Vengeful Retreat":"img/demonHunter/VengefulRetreat.jpg",
    "Void Reaver":"img/demonHunter/VoidReaver.jpg",

    //Druid
    "Moonkin Form":"img/druid/MookinFrom.jpg",
    "Regrowth":"img/druid/Regrowth.jpg",
    "Rejuvenation":"img/druid/Rejuvenation.jpg",
    "Moonfire":"img/druid/Moonfire.jpg",
    "Starfire":"img/druid/Starfire.jpg",
    "Sunfire":"img/druid/Sunfire.jpg",
    "Wild Growth":"img/druid/WildGrowth.jpg",
    "Wrath":"img/druid/Wrath.jpg",
    "Abundance":"img/druid/Abundance.jpg",
    "Aquatic Form":"img/druid/AquaticForm.jpg",
    "Astral Influence":"img/druid/AstralInfluence.jpg",
    "Balance Affinity":"img/druid/BalanceAffinity.jpg",
    "Barkskin":"img/druid/Barkskin.jpg",
    "Bear Form":"img/druid/BearForm.jpg",
    "Berserk":"img/druid/Berserk.jpg",
    "Blood Frenzy":"img/druid/BloodFrenzy.jpg",
    "Bloodtalons":"img/druid/Bloodtalons.jpg",
    "Brambles":"img/druid/Brambles.jpg",
    "Bristling Fur":"img/druid/BristlingFur.jpg",
    "Brutal Slash":"img/druid/BrutalSlash.jpg",
    "Cat Form":"img/druid/CatForm.jpg",
    "Celestial Alignment":"img/druid/CelestialAlignment.jpg",
    "Cenarion Ward":"img/druid/CenarionWard.jpg",
    "Clearcasting":"img/druid/Clearcasting.jpg",
    "Cultivation":"img/druid/Cultivation.jpg",
    "Cyclone":"img/druid/Cyclone.jpg",
    "Dash":"img/druid/Dash.jpg",
    "Earthwarden":"img/druid/Earthwarden.jpg",
    "Eclipse (Lunar)":"img/druid/Eclipse(Lunar).jpg",
    "Eclipse (Solar)":"img/druid/Eclipse(Solar).jpg",
    "Efflorescence":"img/druid/Efflorescence.jpg",
    "Entangling Roots":"img/druid/EntanglingRoots.jpg",
    "Feline Swiftness":"img/druid/FelineSwiftness.jpg",
    "Feral Affinity":"img/druid/FeralAffinity.jpg",
    "Feral Frenzy":"img/druid/FeralFrenzy.jpg",
    "Ferocious Bite":"img/druid/FerociousBite.jpg",
    "Flap":"img/druid/Flap.jpg",
    "Flourish":"img/druid/Flourish.jpg",
    "Force of Nature":"img/druid/ForceofNature.jpg",
    "Frenzied Regeneration":"img/druid/FrenziedRegeneration.jpg",
    "Fury of Elune":"img/druid/FuryofElune.jpg",
    "Galactic Guardian":"img/druid/GalacticGuardian.jpg",
    "Germination":"img/druid/Germination.jpg",
    "Gore":"img/druid/Gore.jpg",
    "Growl":"img/druid/Growl.jpg",
    "Guardian Affinity":"img/druid/GuardianAffinity.jpg",
    "Guardian of Elune":"img/druid/GuardianofElune.jpg",
    "Harmony":"img/druid/Harmony.jpg",
    "Heart of the Wild":"img/druid/HeartoftheWild.jpg",
    "Hibernate":"img/druid/Hibernate.jpg",
    "Incapacitating Roar":"img/druid/IncapacitatingRoar.jpg",
    "Incarnation: Guardian of Ursoc":"img/druid/IncarnationGuardianofUrsoc.jpg",
    "Incarnation: Chosen of Elune":"img/druid/IncarnationChosenofElune.jpg",
    "Incarnation: King of the Jungle":"img/druid/IncarnationKingoftheJungle.jpg",
    "Incarnation: Tree of Life":"img/druid/IncarnationTreeofLife.jpg",
    "Infected Wounds":"img/druid/InfectedWounds.jpg",
    "Inner Peace":"img/druid/InnerPeace.jpg",
    "Innervate":"img/druid/Innervate.jpg",
    "Ironbark":"img/druid/Ironbark.jpg",
    "Ironfur":"img/druid/Ironfur.jpg",
    "Lifebloom":"img/druid/Lifebloom.jpg",
    "Lunar Inspiration":"img/druid/LunarInspiration.jpg",
    "Maim":"img/druid/Maim.jpg",
    "Mangle":"img/druid/Mangle.jpg",
    "Mass Entanglement":"img/druid/MassEntanglement.jpg",
    "Maul":"img/druid/Maul.jpg",
    "Mighty Bash":"img/druid/MightyBash.jpg",
    "Moment of Clarity":"img/druid/MomentofClarity.jpg",
    "Nature's Balance":"img/druid/Nature'sBalance.jpg",
    "Nature's Cure":"img/druid/Nature'sCure.jpg",
    "Nature's Guardian":"img/druid/Nature'sGuardian.jpg",
    "Nature's Swiftness":"img/druid/Nature'sSwiftness.jpg",
    "New Moon":"img/druid/NewMoon.jpg",
    "Half Moon":"img/druid/HalfMoon.jpg",
    "Full Moon":"img/druid/FullMoon.jpg",
    "Nourish":"img/druid/Nourish.jpg",
    "Omen of Clarity":"img/druid/OmenofClarity.jpg",
    "Overgrowth":"img/druid/Overgrowth.jpg",
    "Photosynthesis":"img/druid/Photosynthesis.jpg",
    "Predator":"img/druid/Predator.jpg",
    "Predatory Swiftness":"img/druid/PredatorySwiftness.jpg",
    "Primal Wrath":"img/druid/PrimalWrath.jpg",
    "Prowl":"img/druid/Prowl.jpg",
    "Pulverize":"img/druid/Pulverize.jpg",
    "Rake":"img/druid/Rake.jpg",
    "Razor Claws":"img/druid/RazorClaws.jpg",
    "Rebirth":"img/druid/Rebirth.jpg",
    "Remove Corruption":"img/druid/RemoveCorruption.jpg",
    "Rend and Tear":"img/druid/RendandTear.jpg",
    "Renewal":"img/druid/Renewal.jpg",
    "Restoration Affinity":"img/druid/RestorationAffinity.jpg",
    "Revitalize":"img/druid/Revitalize.jpg",
    "Revive":"img/druid/Revive.jpg",
    "Rip":"img/druid/Rip.jpg",
    "Sabertooth":"img/druid/Sabertooth.jpg",
    "Savage Roar":"img/druid/SavageRoar.jpg",
    "Scent of Blood":"img/druid/ScentofBlood.jpg",
    "Shooting Stars":"img/druid/ShootingStars.jpg",
    "Shred":"img/druid/Shred.jpg",
    "Skull Bash":"img/druid/SkullBash.jpg",
    "Solar Beam":"img/druid/SolarBeam.jpg",
    "Solstice":"img/druid/Solstice.jpg",
    "Soothe":"img/druid/Soothe.jpg",
    "Soul of the Forest":"img/druid/SouloftheForest.jpg",
    "Spring Blossoms":"img/druid/SpringBlossoms.jpg",
    "Stampeding Roar":"img/druid/StampedingRoar.jpg",
    "Starfall":"img/druid/Starfall.jpg",
    "Starlord":"img/druid/Starlord.jpg",
    "Starsurge":"img/druid/Starsurge.jpg",
    "Stellar Drift":"img/druid/StellarDrift.jpg",
    "Stellar Flare":"img/druid/StellarFlare.jpg",
    "Survival Instincts":"img/druid/SurvivalInstincts.jpg",
    "Survival of the Fittest":"img/druid/SurvivaloftheFittest.jpg",
    "Swiftmend":"img/druid/Swiftmend.jpg",
    "Swipe":"img/druid/Swipe.jpg",
    "Thick Hide":"img/druid/ThickHide.jpg",
    "Thrash":"img/druid/Thrash.jpg",
    "Tiger Dash":"img/druid/TigerDash.jpg",
    "Tiger's Fury":"img/druid/Tiger'sFury.jpg",
    "Tooth and Claw":"img/druid/ToothandClaw.jpg",
    "Total Eclipse":"img/druid/.jpg",
    "Tranquility":"img/druid/Tranquility.jpg",
    "Travel Form":"img/druid/TravelForm.jpg",
    "Twin Moons":"img/druid/TwinMoons.jpg",
    "Typhoon":"img/druid/Typhoon.jpg",
    "Ursine Adept":"img/druid/UrsineAdept.jpg",
    "Ursol's Vortex":"img/druid/Ursol'sVortex.jpg",
    "Warrior of Elune":"img/druid/WarriorofElune.jpg",
    "Wild Charge":"img/druid/WildCharge.jpg",
    "Ysera's Gift":"img/druid/Ysera'sGift.jpg",

    //hunter
    "Aimed Shot":"img/hunter/AimedShot.jpg",
    "AlphaPredator":"img/hunter/Alpha Predator.jpg",
    "A Murder of Crows":"img/hunter/AMurderofCrows.jpg",
    "Animal Companion":"img/hunter/AnimalCompanion.jpg",
    "Arcane Shot":"img/hunter/ArcaneShot.jpg",
    "Aspect of the Beast":"img/hunter/AspectoftheBeast.jpg",
    "Aspect of the Eagle":"img/hunter/AspectoftheEagle.jpg",
    "Aspect of the Chameleon":"img/hunter/AspectoftheChameleon.jpg",
    "Aspect of the Cheetah":"img/hunter/AspectoftheCheetah.jpg",
    "Aspect of the Turtle":"img/hunter/AspectoftheTurtle.jpg",
    "Aspect of the Wild":"img/hunter/AspectoftheWild.jpg",
    "Barbed Shot":"img/hunter/BarbedShot.jpg",
    "Barrage":"img/hunter/Barrage.jpg",
    "Beast Cleave":"img/hunter/BeastCleave.jpg",
    "Bestial Wrath":"img/hunter/BestialWrath.jpg",
    "Binding Shackles":"img/hunter/BindingShackles.jpg",
    "Binding Shot":"img/hunter/BindingShot.jpg",
    "Birds of Prey":"img/hunter/BirdsofPrey.jpg",
    "Bloodseeker":"img/hunter/Bloodseeker.jpg",
    "Bloodshed":"img/hunter/Bloodshed.jpg",
    "Born To Be Wild":"img/hunter/BornToBeWild.jpg",
    "Bursting Shot":"img/hunter/BurstingShot.jpg",
    "Butchery":"img/hunter/Butchery.jpg",
    "Calling the Shots":"img/hunter/CallingtheShots.jpg",
    "Call Pet":"img/hunter/CallPet.jpg",
    "Camouflage":"img/hunter/Camouflage.jpg",
    "Careful Aim":"img/hunter/CarefulAim.jpg",
    "Carve":"img/hunter/Carve.jpg",
    "Cobra Shot":"img/hunter/CobraShot.jpg",
    "Command Pet":"img/hunter/CommandPet.jpg",
    "Concussive Shot":"img/hunter/ConcussiveShot.jpg",
    "Coordinated Assault":"img/hunter/CoordinatedAssault.jpg",
    "Counter Shot":"img/hunter/CounterShot.jpg",
    "Dead Eye":"img/hunter/DeadEye.jpg",
    "Dire Beast":"img/hunter/DireBeast.jpg",
    "Disengage":"img/hunter/Disengage.jpg",
    "Dismiss Pet":"img/hunter/DismissPet.jpg",
    "Double Tap":"img/hunter/DoubleTap.jpg",
    "Eagle Eye":"img/hunter/EagleEye.jpg",
    "Exhilaration":"img/hunter/Exhilaration.jpg",
    "Explosive Shot":"img/hunter/ExplosiveShot.jpg",
    "Feign Death":"img/hunter/FeignDeath.jpg",
    "Flanking Strike":"img/hunter/FlankingStrike.jpg",
    "Flare":"img/hunter/Flare.jpg",
    "Freezing Trap":"img/hunter/FreezingTrap.jpg",
    "Guerrilla Tactics":"img/hunter/GuerrillaTactics.jpg",
    "Harpoon":"img/hunter/Harpoon.jpg",
    "Hunter's Mark":"img/hunter/Hunter'sMark.jpg",
    "Hydra's Bite":"img/hunter/Hydra'sBite.jpg",
    "Chakrams":"img/hunter/Chakrams.jpg",
    "Chimaera Shot":"img/hunter/ChimaeraShot.jpg",
    "Intimidation":"img/hunter/Intimidation.jpg",
    "Kill Command":"img/hunter/KillCommand.jpg",
    "Killer Cobra":"img/hunter/KillerCobra.jpg",
    "Killer Instinct":"img/hunter/KillerInstinct.jpg",
    "Kill Shot":"img/hunter/KillShot.jpg",
    "Kindred Spirits":"img/hunter/KindredSpirits.jpg",
    "Lethal Shots":"img/hunter/LethalShots.jpg",
    "Lock and Load":"img/hunter/LockandLoad.jpg",
    "Lone Wolf":"img/hunter/LoneWolf.jpg",
    "Master Marksman":"img/hunter/MasterMarksman.jpg",
    "Master of Beasts":"img/hunter/MasterofBeasts.jpg",
    "Mend Pet":"img/hunter/MendPet.jpg",
    "Misdirection":"img/hunter/Misdirection.jpg",
    "Mongoose Bite":"img/hunter/MongooseBite.jpg",
    "Multi-Shot":"img/hunter/Multi-Shot.jpg",
    "Muzzle":"img/hunter/Muzzle.jpg",
    "Natural Mending":"img/hunter/NaturalMending.jpg",
    "One with the Pack":"img/hunter/OnewiththePack.jpg",
    "Pack Tactics":"img/hunter/PackTactics.jpg",
    "Play Dead":"img/hunter/PlayDead.jpg",
    "Posthaste":"img/hunter/Posthaste.jpg",
    "Precise Shots":"img/hunter/PreciseShots.jpg",
    "Rapid Fire":"img/hunter/RapidFire.jpg",
    "Raptor Strike":"img/hunter/RaptorStrike.jpg",
    "Revive Pet":"img/hunter/RevivePet.jpg",
    "Scare Beast":"img/hunter/ScareBeast.jpg",
    "Scent of Blood(Hunter)":"img/hunter/ScentofBlood.jpg",
    "Serpent Sting":"img/hunter/SerpentSting.jpg",
    "Sniper Training":"img/hunter/SniperTraining.jpg",
    "Spirit Bond":"img/hunter/SpiritBond.jpg",
    "Spitting Cobra":"img/hunter/SpittingCobra.jpg",
    "Stampede":"img/hunter/Stampede.jpg",
    "Steady Focus":"img/hunter/SteadyFocus.jpg",
    "Steady Shot":"img/hunter/SteadyShot.jpg",
    "Steel Trap":"img/hunter/SteelTrap.jpg",
    "Stomp":"img/hunter/Stomp.jpg",
    "Streamline":"img/hunter/Streamline.jpg",
    "Tame Beast":"img/hunter/TameBeast.jpg",
    "Tar Trap":"img/hunter/TarTrap.jpg",
    "Terms of Engagement":"img/hunter/TermsofEngagement.jpg",
    "Thrill of the Hunt":"img/hunter/ThrilloftheHunt.jpg",
    "Tip of the Spear":"img/hunter/TipoftheSpear.jpg",
    "Trailblazer":"img/hunter/Trailblazer.jpg",
    "Tranquilizing Shot":"img/hunter/TranquilizingShot.jpg",
    "Trick Shots":"img/hunter/TrickShots.jpg",
    "True Aim":"img/hunter/TrueAim.jpg",
    "Trueshot":"img/hunter/Trueshot.jpg",
    "Viper's Venom":"img/hunter/Viper'sVenom.jpg",
    "Volley":"img/hunter/Volley.jpg",
    "Volley2":"img/hunter/Volley2.jpg",
    "Wailing Arrow":"img/hunter/WailingArrow.jpg",
    "Wild Call":"img/hunter/WildCall.jpg",
    "Wildfire Bomb":"img/hunter/WildfireBomb.jpg",
    "Wildfire Infusion":"img/hunter/WildfireInfusion.jpg",
    "Wing Clip":"img/hunter/WingClip.jpg",

    //Mage
    "Arcane Blast":"img/mage/ArcaneBlast.jpg",
    "Arcane Barrage":"img/mage/ArcaneBarrage.jpg",
    "Alexstrasza's Fury":"img/mage/Alexstrasza'sFury.jpg",
    "Alter Time":"img/mage/AlterTime.jpg",
    "Amplification":"img/mage/Amplification.jpg",
    "Arcane Echo":"img/mage/ArcaneEcho.jpg",
    "Arcane Explosion":"img/mage/ArcaneExplosion.jpg",
    "Arcane Familiar":"img/mage/ArcaneFamiliar.jpg",
    "Arcane Intellect":"img/mage/ArcaneIntellect.jpg",
    "Arcane Missiles":"img/mage/ArcaneMissiles.jpg",
    "Arcane Orb":"img/mage/ArcaneOrb.jpg",
    "Arcane Power":"img/mage/ArcanePower.jpg",
    "Blast Wave":"img/mage/BlastWave.jpg",
    "Blazing Barrier":"img/mage/BlazingBarrier.jpg",
    "Blazing Soul":"img/mage/BlazingSoul.jpg",
    "Blink":"img/mage/Blink.jpg",
    "Blizzard":"img/mage/Blizzard.jpg",
    "Bone Chilling":"img/mage/BoneChilling.jpg",
    "Brain Freeze":"img/mage/BrainFreeze.jpg",
    "Cauterize":"img/mage/Cauterize.jpg",
    "Cold Snap":"img/mage/ColdSnap.jpg",
    "Combustion":"img/mage/Combustion.jpg",
    "Comet Storm":"img/mage/CometStorm.jpg",
    "Cone of Cold":"img/mage/ConeofCold.jpg",
    "Conflagration":"img/mage/Conflagration.jpg",
    "Conjure Mana Gem":"img/mage/ConjureManaGem.jpg",
    "Conjure Refreshment":"img/mage/ConjureRefreshment.jpg",
    "Counterspell":"img/mage/Counterspell.jpg",
    "Dragon's Breath":"img/mage/Dragon'sBreath.jpg",
    "Ebonbolt":"img/mage/Ebonbolt.jpg",
    "Enlightened":"img/mage/Enlightened.jpg",
    "Evocation":"img/mage/Evocation.jpg",
    "Fingers of Frost":"img/mage/FingersofFrost.jpg",
    "Fireball":"img/mage/Fireball.jpg",
    "Fire Blast":"img/mage/FireBlast.jpg",
    "Firestarter":"img/mage/Firestarter.jpg",
    "Flame On":"img/mage/FlameOn.jpg",
    "Flame Patch":"img/mage/FlamePatch.jpg",
    "Flamestrike":"img/mage/Flamestrike.jpg",
    "Flurry":"img/mage/Flurry.jpg",
    "Focus Magic":"img/mage/FocusMagic.jpg",
    "Freeze":"img/mage/Freeze.jpg",
    "Freezing Rain":"img/mage/FreezingRain.jpg",
    "Frenetic Speed":"img/mage/FreneticSpeed.jpg",
    "Frigid Winds":"img/mage/FrigidWinds.jpg",
    "From the Ashes":"img/mage/FromtheAshes.jpg",
    "Frostbolt":"img/mage/Frostbolt.jpg",
    "Frost Nova":"img/mage/FrostNova.jpg",
    "Frozen Orb":"img/mage/FrozenOrb.jpg",
    "Frozen Touch":"img/mage/FrozenTouch.jpg",
    "Glacial Insulation":"img/mage/GlacialInsulation.jpg",
    "Glacial Spike":"img/mage/GlacialSpike.jpg",
    "Greater Invisibility":"img/mage/GreaterInvisibility.jpg",
    "Hot Streak":"img/mage/HotStreak.jpg",
    "Chain Reaction":"img/mage/ChainReaction.jpg",
    "Chrono Shift":"img/mage/ChronoShift.jpg",
    "Ice Barrier":"img/mage/IceBarrier.jpg",
    "Ice Block":"img/mage/IceBlock.jpg",
    "Ice Floes":"img/mage/IceFloes.jpg",
    "Ice Lance":"img/mage/IceLance.jpg",
    "Ice Nova":"img/mage/IceNova.jpg",
    "Ice Ward":"img/mage/IceWard.jpg",
    "Icicles":"img/mage/Icicles.jpg",
    "Icy Veins":"img/mage/IcyVeins.jpg",
    "Ignite":"img/mage/Ignite.jpg",
    "Illusion":"img/mage/Illusion.jpg",
    "Incanter's Flow":"img/mage/Incanter'sFlow.jpg",
    "Invisibility":"img/mage/Invisibility.jpg",
    "Kindling":"img/mage/Kindling.jpg",
    "Living Bomb":"img/mage/LivingBomb.jpg",
    "Lonely Winter":"img/mage/LonelyWinter.jpg",
    "Master of Time":"img/mage/MasterofTime.jpg",
    "Meteor":"img/mage/Meteor.jpg",
    "Mirror Image":"img/mage/MirrorImage.jpg",
    "Nether Tempest":"img/mage/NetherTempest.jpg",
    "Overpowered":"img/mage/Overpowered.jpg",
    "Phoenix Flames":"img/mage/PhoenixFlames.jpg",
    "Polymorph":"img/mage/Polymorph.jpg",
    "Presence of Mind":"img/mage/PresenceofMind.jpg",
    "Prismatic Barrier":"img/mage/PrismaticBarrier.jpg",
    "Pyroblast":"img/mage/Pyroblast.jpg",
    "Pyroclasm":"img/mage/Pyroclasm.jpg",
    "Pyromaniac":"img/mage/Pyromaniac.jpg",
    "Ray of Frost":"img/mage/RayofFrost.jpg",
    "Remove Curse":"img/mage/RemoveCurse.jpg",
    "Resonance":"img/mage/Resonance.jpg",
    "Reverberate":"img/mage/Reverberate.jpg",
    "Ring of Frost":"img/mage/RingofFrost.jpg",
    "Rule of Threes":"img/mage/RuleofThrees.jpg",
    "Rune of Power":"img/mage/RuneofPower.jpg",
    "Savant":"img/mage/Savant.jpg",
    "Scorch":"img/mage/Scorch.jpg",
    "Searing Touch":"img/mage/SearingTouch.jpg",
    "Shatter":"img/mage/Shatter.jpg",
    "Shimmer":"img/mage/Shimmer.jpg",
    "Slipstream":"img/mage/Slipstream.jpg",
    "Slow":"img/mage/Slow.jpg",
    "Slow Fall":"img/mage/SlowFall.jpg",
    "Spellsteal":"img/mage/Spellsteal.jpg",
    "Summon Water Elemental":"img/mage/SummonWaterElemental.jpg",
    "Supernova":"img/mage/Supernova.jpg",
    "Thermal Void":"img/mage/ThermalVoid.jpg",
    "Time Anomaly":"img/mage/TimeWarp.jpg",
    "Time Warp":"img/mage/TimeWarp.jpg",
    "Touch of the Magi":"img/mage/TouchoftheMagi.jpg",

    //Monk
    "Vivify":"img/monk/Vivify.jpg",
    "Renewing Mist":"img/monk/RenewingMist.jpg",
    "Mana Tea":"img/monk/ManaTea.jpg",
    "Blackout Kick":"img/monk/BlackoutKick.jpg",
    "Chi-Ji":"img/monk/Chi-Ji.jpg", //???
    "Chi Burst":"img/monk/ChiBurst.jpg",
    "Detox":"img/monk/Detox.jpg",
    "Enveloping Breath":"img/monk/EnvelopingBreath.jpg",
    "Enveloping Mist":"img/monk/EnvelopingMist.jpg",
    "Essence Font":"img/monk/EssenceFont.jpg",
    "Expel Harm":"img/monk/ExpelHarm.jpg",
    "Fortifying Brew":"img/monk/FortifyingBrew2.jpg",
    "Gust of Mists":"img/monk/GustofMists.jpg",
    "Life Cocoon":"img/monk/LifeCocoon.jpg",
    "Provoke":"img/monk/Provoke.jpg",
    "Refreshing Jade Wind":"img/monk/RefreshingJadeWind.jpg",
    "Revival":"img/monk/Revival.jpg",
    "Rising Mist":"img/monk/RisingMist.jpg",
    "Rising Sun Kick":"img/monk/RisingSunKick.jpg",
    "Roll":"img/monk/Roll.jpg",
    "Soothing Mist":"img/monk/SoothingMist.jpg",
    "Spinning Crane Kick":"img/monk/SpinningCraneKick.jpg",
    "Thunder Focus Tea":"img/monk/ThunderFocusTea.jpg",
    "Tiger Palm":"img/monk/TigerPalm.jpg",
    "Tiger's Lust":"img/monk/TigersLust.jpg",
    "Touch Of Death":"img/monk/TouchOfDeath.jpg",
    "Yu'Lon":"img/monk/Yu'Lon.jpg",
    "Teachings of the Monastery":"img/monk/TeachingsOfTheMonastery.jpg",
    "Mystic Touch":"img/monk/MysticTouch.jpg",
    "Stagger":"img/monk/Stagger.jpg",
    "Light Stagger":"img/monk/LightStagger.jpg",
    "Moderate Stagger":"img/monk/ModerateStagger.jpg",
    "Heavy Stagger":"img/monk/HeavyStagger.jpg",
    "Breath Of Fire":"img/monk/BreathOfFire.jpg",
    "Celestial Brew":"img/monk/CelestialBrew.jpg",
    "Celestial Fortune":"img/monk/CelestialFortune.jpg",
    "Clash":"img/monk/Clash.jpg",
    "Gift Of The Ox":"img/monk/GiftOfTheOx.jpg",
    "Invoke Niuzao, the Black Ox":"img/monk/InvokeNiuzaotheBlackOx.jpg",
    "KegSmash":"img/monk/KegSmash.jpg",
    "Purifying Brew":"img/monk/PurifyingBrew.jpg",
    "Shuffle":"img/monk/Shuffle.jpg",
    "Spear Hand Strike":"img/monk/SpearHandStrike.jpg",
    "Zen Meditation":"img/monk/ZenMeditation.jpg",
    "Combo Strikes":"img/monk/ComboStrikes.jpg",
    "Disable":"img/monk/Disable.jpg",
    "Fists Of Fury":"img/monk/FistsOfFury.jpg",
    "Flying Serpent Kick":"img/monk/FlyingSerpentKick.jpg",
    "Invoke Xuen, the White Tiger":"img/monk/InvokeXuentheWhiteTiger.jpg",
    "Reawaken":"img/monk/Reawaken.jpg",
    "Storm, Earth And Fire":"img/monk/StormEarthAndFire.jpg",
    "Touch Of Karma":"img/monk/TouchOfKarma.jpg",
    "Windwalking":"img/monk/Windwalking.jpg",
    "Resuscitate":"img/monk/Resuscitate.jpg",
    "Chi Torpedo":"img/monk/ChiTorpedo.jpg",
    "Crackling Jade Lightning":"img/monk/CracklingJadeLightning.jpg",
    "Paralysis":"img/monk/Paralysis.jpg",
    "Transcendence":"img/monk/Transcendence.jpg",
    "Transcendence: Transfer":"img/monk/TranscendenceTransfer.jpg",
    "Focused Thunder":"img/monk/focusedThunder.jpg",
    "Chi of the Crane":"img/monk/chiofthecrane.jpg",
    "Summon Jade Serpent Statue":"img/monk/jadestatue.jpg",
    "Life Cycles":"img/monk/lifeCycles.jpg",
    "Mist Wrap":"img/monk/mistWrap.jpg",
    "Upwelling":"img/monk/upwelling.jpg",
    "Rushing Jade Wind":"img/monk/RefreshingJadeWind.jpg",
    "Good Karma":"img/monk/TouchOfKarma.jpg",
    "Ascension":"img/monk/Ascension.jpg",
    "Blackout Combo":"img/monk/BlackoutCombo.jpg",
    "Black Ox Brew":"img/monk/BlackOxBrew.jpg",
    "Bob and Weave":"img/monk/BobandWeave.jpg",
    "Celerity":"img/monk/Celerity.jpg",
    "Celestial Flames":"img/monk/CelestialFlames.jpg",
    "Dampen Harm":"img/monk/DampenHarm.jpg",
    "Diffuse Magic":"img/monk/DiffuseMagic.jpg",
    "Energizing Elixir":"img/monk/EnergizingElixir.jpg",
    "Exploding Keg":"img/monk/ExplodingKeg.jpg",
    "Eye of the Tiger":"img/monk/EyeoftheTiger.jpg",
    "Fist of the White Tiger":"img/monk/FistoftheWhiteTiger.jpg",
    "High Tolerance":"img/monk/HighTolerance.jpg",
    "Hit Combo":"img/monk/HitCombo.jpg",
    "Chi Wave":"img/monk/ChiWave.jpg",
    "Inner Strength":"img/monk/InnerStrength.jpg",
    "Light Brewing":"img/monk/LightBrewing.jpg",
    "Ring of Peace":"img/monk/RingofPeace.jpg",
    "Serenity":"img/monk/Serenity.jpg",
    "Song of Chi-Ji":"img/monk/SongofChi-Ji.jpg",
    "Special Delivery":"img/monk/SpecialDelivery.jpg",
    "Spirit of the Crane":"img/monk/SpiritoftheCrane.jpg",
    "Spiritual Focus":"img/monk/SpiritualFocus.jpg",
    "Spitfire":"img/monk/Spitfire.jpg",
    "Tiger Tail Sweep":"img/monk/TigerTailSweep.jpg",
    "Whirling Dragon Punch":"img/monk/WhirlingDragonPunch.jpg",

    //Paladin
    "Absolution":"img/paladin/Absolution.jpg",
    "Aegis of Light":"img/paladin/AegisofLight.jpg",
    "Ardent Defender":"img/paladin/ArdentDefender.jpg",
    "Art of War":"img/paladin/ArtofWar.jpg",
    "Aura Mastery":"img/paladin/AuraMastery.jpg",
    "Avenger's Shield":"img/paladin/Avenger'sShield.jpg",
    "Avenging Crusader":"img/paladin/AvengingCrusader.jpg",
    "Avenging Wrath":"img/paladin/AvengingWrath.jpg",
    "Awakening":"img/paladin/Awakening.jpg",
    "Beacon of Faith":"img/paladin/BeaconofFaith.jpg",
    "Beacon of Light":"img/paladin/BeaconofLight.jpg",
    "Beacon of Virtue":"img/paladin/BeaconofVirtue.jpg",
    "Bestow Faith":"img/paladin/BestowFaith.jpg",
    "Blade of Justice":"img/paladin/BladeofJustice.jpg",
    "Bladeof Wrath":"img/paladin/BladeofJustice.jpg",
    "Blessed Hammer":"img/paladin/BlessedHammer.jpg",
    "Blessing of Freedom":"img/paladin/BlessingofFreedom.jpg",
    "Blessing of Protection":"img/paladin/BlessingofProtection.jpg",
    "Blessing of Sacrifice":"img/paladin/BlessingofSacrifice.jpg",
    "Blessing of Spellwarding":"img/paladin/BlessingofSpellwarding.jpg",
    "Blinding Light":"img/paladin/BlindingLight.jpg",
    "Cavalier":"img/paladin/Cavalier.jpg",
    "Cleanse":"img/paladin/Cleanse.jpg",
    "Cleanse Toxins":"img/paladin/CleanseToxins.jpg",
    "Concentration Aura":"img/paladin/ConcentrationAura.jpg",
    "Consecrated Ground":"img/paladin/ConsecratedGround.jpg",
    "Consecration":"img/paladin/Consecration.jpg",
    "Contemplation":"img/paladin/Contemplation.jpg",
    "Crusade":"img/paladin/Crusade.jpg",
    "Crusader Aura":"img/paladin/CrusaderAura.jpg",
    "Crusader's Judgment":"img/paladin/Crusader'sJudgment.jpg",
    "Crusader's Might":"img/paladin/Crusader'sMight.jpg",
    "Crusader Strike":"img/paladin/CrusaderStrike.jpg",
    "Devotion Aura":"img/paladin/DevotionAura.jpg",
    "Divine Bulwark":"img/paladin/DivineBulwark.jpg",
    "Divine Protection":"img/paladin/DivineProtection.jpg",
    "Divine Purpose":"img/paladin/DivinePurpose.jpg",
    "Divine Shield":"img/paladin/DivineShield.jpg",
    "Divine Steed":"img/paladin/DivineSteed.jpg",
    "Divine Storm":"img/paladin/DivineStorm.jpg",
    "Empyrean Power":"img/paladin/EmpyreanPower.jpg",
    "Execution Sentence":"img/paladin/ExecutionSentence.jpg",
    "Eye for an Eye":"img/paladin/EyeforanEye.jpg",
    "Final Reckoning":"img/paladin/FinalReckoning.jpg",
    "Final Stand":"img/paladin/FinalStand.jpg",
    "Fires of Justice":"img/paladin/FiresofJustice.jpg",
    "First Avenger":"img/paladin/FirstAvenger.jpg",
    "Fist of Justice":"img/paladin/FistofJustice.jpg",
    "Flash of Light":"img/paladin/FlashofLight.jpg",
    "Glimmer of Light":"img/paladin/GlimmerofLight.jpg",
    "Grand Crusader":"img/paladin/GrandCrusader.jpg",
    "Guardian of AncientKings":"img/paladin/GuardianofAncientKings.jpg",
    "Hammer of Justice":"img/paladin/HammerofJustice.jpg",
    "Hammer of the Righteous":"img/paladin/HammeroftheRighteous.jpg",
    "Hammer of Wrath":"img/paladin/HammerofWrath.jpg",
    "Hand of Hindrance":"img/paladin/HandofHindrance.jpg",
    "Hand of Light":"img/paladin/HandofLight.jpg",
    "Hand of Reckoning":"img/paladin/HandofReckoning.jpg",
    "Hand of theProtector":"img/paladin/HandoftheProtector.jpg",
    "Healing Hands":"img/paladin/HealingHands.jpg",
    "Holy Avenger":"img/paladin/HolyAvenger.jpg",
    "Holy Light":"img/paladin/HolyLight.jpg",
    "Holy Prism":"img/paladin/HolyPrism.jpg",
    "Holy Shield":"img/paladin/HolyShield.jpg",
    "Holy Shock":"img/paladin/HolyShock.jpg",
    "Infusion of Light":"img/paladin/InfusionofLight.jpg",
    "Judgment":"img/paladin/Judgment.jpg",
    "Judgment of Light":"img/paladin/JudgmentofLight.jpg",
    "Justicar's Vengeance":"img/paladin/Justicar'sVengeance.jpg",
    "Lay on Hands":"img/paladin/LayonHands.jpg",
    "Light bringer":"img/paladin/Lightbringer.jpg",
    "Light of Dawn":"img/paladin/LightofDawn.jpg",
    "Lightofthe Martyr":"img/paladin/LightoftheMartyr.jpg",
    "Light's Hammer":"img/paladin/Light'sHammer.jpg",
    "Moment of Glory":"img/paladin/MomentofGlory.jpg",
    "Rebuke":"img/paladin/Rebuke.jpg",
    "Redemption":"img/paladin/Redemption.jpg",
    "Redoubt":"img/paladin/Redoubt.jpg",
    "Repentance":"img/paladin/Repentance.jpg",
    "Retribution Aura":"img/paladin/RetributionAura.jpg",
    "Righteous Fury":"img/paladin/RighteousFury.jpg",
    "Righteous Protector":"img/paladin/RighteousProtector.jpg",
    "Righteous Verdict":"img/paladin/RighteousVerdict.jpg",
    "Rule of Law":"img/paladin/RuleofLaw.jpg",
    "Sanctified Wrath":"img/paladin/SanctifiedWrath.jpg",
    "Saved by the Light":"img/paladin/SavedbytheLight.jpg",
    "Selfless Healer":"img/paladin/SelflessHealer.jpg",
    "Sense Undead":"img/paladin/SenseUndead.jpg",
    "Seraphim":"img/paladin/Seraphim.jpg",
    "Shield of the Righteous":"img/paladin/ShieldoftheRighteous.jpg",
    "Shield of Vengeance":"img/paladin/ShieldofVengeance.jpg",
    "Shining Light":"img/paladin/ShiningLight.jpg",
    "Templar's Verdict":"img/paladin/Templar'sVerdict.jpg",
    "Turn Evil":"img/paladin/TurnEvil.jpg",
    "Unbreakable Spirit":"img/paladin/UnbreakableSpirit.jpg",
    "Wake of Ashes":"img/paladin/WakeofAshes.jpg",
    "Word of Glory":"img/paladin/WordofGlory.jpg",
    "Zeal":"img/paladin/Zeal.jpg",

    //Priest

    //Rogue
    "Garrote":"img/rogue/Garrote.jpg",
    "Mutilate":"img/rogue/Mutilate.jpg",
    "Rupture":"img/rogue/Rupture.jpg",
    "Slice And Dice":"img/rogue/SliceAndDice.jpg",
    "Envenom":"img/rogue/Envenom.jpg",
    "Deadly Poison":"img/rogue/DeadlyPoison.jpg",

    //Shaman
    "Healing Surge":"img/shaman/HealingSurge.jpg",
    "Flame Shock":"img/shaman/FlameShock.jpg",
    "Lightning Bolt":"img/shaman/LightningBolt.jpg",
    "Lava Burst":"img/shaman/LavaBurst.jpg",
    "Healing Rain":"img/shaman/HealingRain.jpg",
    "Healing Tide Totem":"img/shaman/HealingTideTotem.jpg",
    "Ghost Wolf":"img/shaman/GhostWolf.jpg",
    "Riptide":"img/shaman/Riptide.jpg",
}