let iconsPath = {
    //
    "dps":"img/roles/role_dps.png",
    "healer":"img/roles/role_healer.png",
    "tank":"img/roles/role_tank.png",
    //specs
    specs: {
        "mistweaver":"img/specs/monk/mistweaver.png",
        "windwalker":"img/specs/monk/windwalker.png",
        "brewmaster":"img/specs/monk/brewmaster.png",
        "restorationShaman":"img/specs/shaman/restoration.png",
        "elemental":"img/specs/shaman/elemental.png",
        "assassination":"img/specs/rogue/assassination.png",
        "restorationDruid":"img/specs/druid/restoration.png",
        "balance":"img/specs/druid/balance.png",
        "arcane":"img/specs/mage/arcane.png",
        "havoc":"img/specs/demonhunter/havoc.jpg",
    },

    //classes
    classes: {
        "Death Knight":"img/classes/deathknight.png",
        "Demon Hunter":"img/classes/demonhunter.jpg",
        "Druid":"img/classes/druid.png",
        "Hunter":"img/classes/hunter.png",
        "Mage":"img/classes/mage.png",
        "Monk":"img/classes/monk.png",
        "Paladin":"img/classes/paladin.png",
        "Priest":"img/classes/priest.png",
        "Rogue":"img/classes/rogue.png",
        "Shaman":"img/classes/shaman.png",
        "Warlock":"img/classes/warlock.png",
        "Warrior":"img/classes/warrior.png",
    },

    "Mana Potion":"img/ManaPotion.jpg",
    "Auto Attack":"img/AutoAttack.jpg",
    "Leech":"img/Leech.jpg",

    //Death Knight
    "All Will Serve":"img/deathKnight/AllWillServe.jpg",
    "Blooddrinker":"img/deathKnight/Blooddrinker.jpg",
    "Breath of Sindragosa":"img/deathKnight/BreathofSindragosa.jpg",
    "Frostscythe":"img/deathKnight/Frostscythe.jpg",
    "Gathering Storm":"img/deathKnight/GatheringStorm.jpg",
    "Glacial Advance":"img/deathKnight/GlacialAdvance.jpg",
    "Horn of Winter":"img/deathKnight/HornofWinter.jpg",
    "Inexorable Assault":"img/deathKnight/InexorableAssault.jpg",
    "Pestilence":"img/deathKnight/Pestilence.jpg",
    "Purgatory":"img/deathKnight/Purgatory.jpg",
    "Rapid Decomposition":"img/deathKnight/RapidDecomposition.jpg",
    "Soul Reaper":"img/deathKnight/SoulReaper.jpg",
    "Summon Gargoyle":"img/deathKnight/SummonGargoyle.jpg",
    "Wraith Walk":"img/deathKnight/WraithWalk.jpg",
    "Anti-Magic Barrier":"img/deathKnight/Anti-MagicBarrier.jpg",
    "Army of the Damned":"img/deathKnight/ArmyoftheDamned.jpg",
    "Asphyxiate":"img/deathKnight/Asphyxiate.jpg",
    "Avalanche":"img/deathKnight/Avalanche.jpg",
    "Blinding Sleet":"img/deathKnight/BlindingSleet.jpg",
    "Blood Tap":"img/deathKnight/BloodTap.jpg",
    "Bloodworms":"img/deathKnight/Bloodworms.jpg",
    "Bonestorm":"img/deathKnight/Bonestorm.jpg",
    "Bursting Sores":"img/deathKnight/BurstingSores.jpg",
    "Clawing Shadows":"img/deathKnight/ClawingShadows.jpg",
    "Cold Heart":"img/deathKnight/ColdHeart.jpg",
    "Consumption":"img/deathKnight/Consumption.jpg",
    "Death Pact":"img/deathKnight/DeathPact.jpg",
    "Death's Reach":"img/deathKnight/DeathsReach.jpg",
    "Defile":"img/deathKnight/Defile.jpg",
    "Ebon Fever":"img/deathKnight/EbonFever.jpg",
    "Foul Bulwark":"img/deathKnight/FoulBulwark.jpg",
    "Frozen Pulse":"img/deathKnight/FrozenPulse.jpg",
    "Grip of the Dead":"img/deathKnight/GripoftheDead.jpg",
    "Harbinger of Doom":"img/deathKnight/HarbingerofDoom.jpg",
    "Heartbreaker":"img/deathKnight/Heartbreaker.jpg",
    "Hemostasis":"img/deathKnight/Hemostasis.jpg",
    "Hypothermic Presence":"img/deathKnight/HypothermicPresence.jpg",
    "Icecap":"img/deathKnight/Icecap.jpg",
    "Icy Talons":"img/deathKnight/IcyTalons.jpg",
    "Infected Claws":"img/deathKnight/InfectedClaws.jpg",
    "Mark of Blood":"img/deathKnight/MarkofBlood.jpg",
    "Murderous Efficiency":"img/deathKnight/MurderousEfficiency.jpg",
    "Obliteration":"img/deathKnight/Obliteration.jpg",
    "Permafrost":"img/deathKnight/Permafrost.jpg",
    "Pestilent Pustules":"img/deathKnight/PestilentPustules.jpg",
    "Red Thirst":"img/deathKnight/RedThirst.jpg",
    "Relishin Blood":"img/deathKnight/RelishinBlood.jpg",
    "Spell Eater":"img/deathKnight/SpellEater.jpg",
    "Tightening Grasp":"img/deathKnight/TighteningGrasp.jpg",
    "Tombstone":"img/deathKnight/Tombstone.jpg",
    "Unholy Assault":"img/deathKnight/UnholyAssault.jpg",
    "Unholy Blight":"img/deathKnight/UnholyBlight.jpg",
    "Unholy Pact":"img/deathKnight/UnholyPact.jpg",
    "Voracious":"img/deathKnight/Voracious.jpg",
    "Anti-Magic Shell":"img/deathKnight/Anti-MagicShell.jpg",
    "Anti-Magic Zone":"img/deathKnight/Anti-Magic Zone.jpg",
    "Apocalypse":"img/deathKnight/Apocalypse.jpg",
    "Army of the Dead":"img/deathKnight/ArmyoftheDead.jpg",
    "Blood Boil":"img/deathKnight/BloodBoil.jpg",
    "Blood Plague":"img/deathKnight/BloodPlague.jpg",
    "Blood Shield":"img/deathKnight/BloodShield.jpg",
    "Control Undead":"img/deathKnight/ControlUndead.jpg",
    "Corpse Exploder":"img/deathKnight/CorpseExploder.jpg",
    "Crimson Scourge":"img/deathKnight/CrimsonScourge.jpg",
    "Dancing Rune Weapon":"img/deathKnight/DancingRuneWeapon.jpg",
    "Dark Command":"img/deathKnight/DarkCommand.jpg",
    "Dark Succor":"img/deathKnight/DarkSuccor.jpg",
    "Dark Transformation":"img/deathKnight/DarkTransformation.jpg",
    "Death and Decay":"img/deathKnight/DeathandDecay.jpg",
    "Death Coil":"img/deathKnight/DeathCoil.jpg",
    "Death Grip":"img/deathKnight/DeathGrip.jpg",
    "Deaths Advance":"img/deathKnight/DeathsAdvance.jpg",
    "Deaths Caress":"img/deathKnight/DeathsCaress.jpg",
    "Death Strike":"img/deathKnight/DeathStrike.jpg",
    "Dreadblade":"img/deathKnight/Dreadblade.jpg",
    "Empower Rune Weapon":"img/deathKnight/EmpowerRuneWeapon.jpg",
    "Epidemic":"img/deathKnight/Epidemic.jpg",
    "Festering Strike":"img/deathKnight/FesteringStrike.jpg",
    "Festering Wound":"img/deathKnight/FesteringWound.jpg",
    "Frost Breath":"img/deathKnight/FrostBreath.jpg",
    "Frost Fever":"img/deathKnight/FrostFever.jpg",
    "Frost Strike":"img/deathKnight/FrostStrike.jpg",
    "Frostwyrm's Fury":"img/deathKnight/FrostwyrmsFury.jpg",
    "Frozen Heart":"img/deathKnight/FrozenHeart.jpg",
    "Gorefiends Grasp":"img/deathKnight/GorefiendsGrasp.jpg",
    "HeartS trike":"img/deathKnight/HeartStrike.jpg",
    "Howling Blast":"img/deathKnight/Howling Blast.jpg",
    "Chains of Ice":"img/deathKnight/ChainsofIce.jpg",
    "Icebound Fortitude":"img/deathKnight/IceboundFortitude.jpg",
    "Killing Machine":"img/deathKnight/KillingMachine.jpg",
    "Lichborne":"img/deathKnight/Lichborne.jpg",
    "Marrowrend":"img/deathKnight/Marrowrend.jpg",
    "Mind Freeze":"img/deathKnight/MindFreeze.jpg",
    "Obliterate":"img/deathKnight/Obliterate.jpg",
    "Ossuary":"img/deathKnight/Ossuary.jpg",
    "Outbreak":"img/deathKnight/Outbreak.jpg",
    "Path of Frost":"img/deathKnight/PathofFrost.jpg",
    "Pillar of Frost":"img/deathKnight/PillarofFrost.jpg",
    "Raise Ally":"img/deathKnight/RaiseAlly.jpg",
    "Raise Dead":"img/deathKnight/RaiseDead.jpg",
    "Remorseless Winter":"img/deathKnight/RemorselessWinter.jpg",
    "Rime":"img/deathKnight/Rime.jpg",
    "Rune Strike":"img/deathKnight/RuneStrike.jpg",
    "Rune Tap":"img/deathKnight/RuneTap.jpg",
    "Runic Corruption":"img/deathKnight/RunicCorruption.jpg",
    "Sacrificial Pact":"img/deathKnight/SacrificialPact.jpg",
    "Scourge Strike":"img/deathKnight/ScourgeStrike.jpg",
    "Sudden Doom":"img/deathKnight/SuddenDoom.jpg",
    "Vampiric Blood":"img/deathKnight/VampiricBlood.jpg",
    "Veteran of the Third War":"img/deathKnight/VeteranoftheThirdWar.jpg",

    //Demon Hunter
    "Chaos Brand":"img/demonHunter/ChaosBrand.jpg",
    "Annihilation":"img/demonHunter/Annihilation.jpg",
    "Blade Dance":"img/demonHunter/BladeDance.jpg",
    "Death Sweep":"img/demonHunter/DeathSweep.jpg",
    "Demon's Bite":"img/demonHunter/DemonsBite.jpg",
    "Eye Beam":"img/demonHunter/EyeBeam.jpg",
    "Chaos Strike":"img/demonHunter/ChaosStrike.jpg",
    "Immolation Aura":"img/demonHunter/ImmolationAura.jpg",
    "Metamorphosis":"img/demonHunter/Metamorphosis.jpg",
    "Abyssal Strike":"img/demonHunter/AbyssalStrike.jpg",
    "Agonizing Flames":"img/demonHunter/AgonizingFlames.jpg",
    "Blind Fury":"img/demonHunter/BlindFury.jpg",
    "Blur":"img/demonHunter/Blur.jpg",
    "Bulk Extraction":"img/demonHunter/BulkExtraction.jpg",
    "Burning Alive":"img/demonHunter/BurningAlive.jpg",
    "Burning Hatred":"img/demonHunter/BurningHatred.jpg",
    "Concentrated Sigils":"img/demonHunter/ConcentratedSigils.jpg",
    "Consume Magic":"img/demonHunter/ConsumeMagic.jpg",
    "Cycle of Hatred":"img/demonHunter/CycleofHatred.jpg",
    "Darkness":"img/demonHunter/Darkness.jpg",
    "Demon Blades":"img/demonHunter/DemonBlades.jpg",
    "Demonic":"img/demonHunter/Demonic.jpg",
    "Demonic Appetite":"img/demonHunter/DemonicAppetite.jpg",
    "Demonic Presence":"img/demonHunter/DemonicPresence.jpg",
    "Demonic Wards":"img/demonHunter/DemonicWards.jpg",
    "Demon Spikes":"img/demonHunter/DemonSpikes.jpg",
    "Desperate Instincts":"img/demonHunter/DesperateInstincts.jpg",
    "Disrupt":"img/demonHunter/Disrupt.jpg",
    "Essence Break":"img/demonHunter/EssenceBreak.jpg",
    "Fallout":"img/demonHunter/Fallout.jpg",
    "Feast of Souls":"img/demonHunter/FeastofSouls.jpg",
    "Feed the Demon":"img/demonHunter/FeedtheDemon.jpg",
    "Fel Barrage":"img/demonHunter/FelBarrage.jpg",
    "Fel blade":"img/demonHunter/Felblade.jpg",
    "Fel Blood":"img/demonHunter/FelBlood.jpg",
    "Fel Devastation":"img/demonHunter/FelDevastation.jpg",
    "Fel Eruption":"img/demonHunter/FelEruption.jpg",
    "Fel Rush":"img/demonHunter/FelRush.jpg",
    "Fiery Brand":"img/demonHunter/FieryBrand.jpg",
    "First Blood":"img/demonHunter/FirstBlood.jpg",
    "Fracture":"img/demonHunter/Fracture.jpg",
    "Glaive Tempest":"img/demonHunter/GlaiveTempest.jpg",
    "Glide":"img/demonHunter/Glide.jpg",
    "Chaos Nova":"img/demonHunter/ChaosNova.jpg",
    "Charred Flesh":"img/demonHunter/CharredFlesh.jpg",
    "Imprison":"img/demonHunter/Imprison.jpg",
    "Infernal Armor":"img/demonHunter/InfernalArmor.jpg",
    "Infernal Strike":"img/demonHunter/InfernalStrike.jpg",
    "Insatiable Hunger":"img/demonHunter/InsatiableHunger.jpg",
    "Last Resort":"img/demonHunter/LastResort.jpg",
    "Master of the Glaive":"img/demonHunter/MasteroftheGlaive.jpg",
    "Momentum":"img/demonHunter/Momentum.jpg",
    "Netherwalk":"img/demonHunter/Netherwalk.jpg",
    "Quickened Sigils":"img/demonHunter/QuickenedSigils.jpg",
    "Revelin Pain":"img/demonHunter/RevelinPain.jpg",
    "Ruinous Bulwark":"img/demonHunter/RuinousBulwark.jpg",
    "Shattered Souls":"img/demonHunter/ShatteredSouls.jpg",
    "Shear":"img/demonHunter/Shear.jpg",
    "Sigil of Flame":"img/demonHunter/SigilofFlame.jpg",
    "Sigil of Chains":"img/demonHunter/SigilofChains.jpg",
    "Sigil of Misery":"img/demonHunter/SigilofMisery.jpg",
    "Sigil of Silence":"img/demonHunter/SigilofSilence.jpg",
    "Soul Barrier":"img/demonHunter/SoulBarrier.jpg",
    "Soul Carver":"img/demonHunter/SoulCarver.jpg",
    "Soul Cleave":"img/demonHunter/SoulCleave.jpg",
    "Soul Rending":"img/demonHunter/SoulRending.jpg",
    "Spectral Sight":"img/demonHunter/SpectralSight.jpg",
    "Spirit Bomb":"img/demonHunter/SpiritBomb.jpg",
    "Thick Skin":"img/demonHunter/ThickSkin.jpg",
    "Throw Glaive":"img/demonHunter/ThrowGlaive.jpg",
    "Torment":"img/demonHunter/Torment.jpg",
    "Trail of Ruin":"img/demonHunter/TrailofRuin.jpg",
    "Unbound Chaos":"img/demonHunter/UnboundChaos.jpg",
    "Unleashed Power":"img/demonHunter/UnleashedPower.jpg",
    "Vengeful Retreat":"img/demonHunter/VengefulRetreat.jpg",
    "Void Reaver":"img/demonHunter/VoidReaver.jpg",

    //Druid
    "Moonkin Form":"img/druid/MookinFrom.jpg",
    "Regrowth":"img/druid/Regrowth.jpg",
    "Rejuvenation":"img/druid/Rejuvenation.jpg",
    "Moonfire":"img/druid/Moonfire.jpg",
    "Starfire":"img/druid/Starfire.jpg",
    "Sunfire":"img/druid/Sunfire.jpg",
    "Wild Growth":"img/druid/WildGrowth.jpg",
    "Wrath":"img/druid/Wrath.jpg",
    "Abundance":"img/druid/Abundance.jpg",
    "Aquatic Form":"img/druid/AquaticForm.jpg",
    "Astral Influence":"img/druid/AstralInfluence.jpg",
    "Balance Affinity":"img/druid/BalanceAffinity.jpg",
    "Barkskin":"img/druid/Barkskin.jpg",
    "Bear Form":"img/druid/BearForm.jpg",
    "Berserk":"img/druid/Berserk.jpg",
    "Blood Frenzy":"img/druid/BloodFrenzy.jpg",
    "Bloodtalons":"img/druid/Bloodtalons.jpg",
    "Brambles":"img/druid/Brambles.jpg",
    "Bristling Fur":"img/druid/BristlingFur.jpg",
    "Brutal Slash":"img/druid/BrutalSlash.jpg",
    "Cat Form":"img/druid/CatForm.jpg",
    "Celestial Alignment":"img/druid/CelestialAlignment.jpg",
    "Cenarion Ward":"img/druid/CenarionWard.jpg",
    "Clearcasting":"img/druid/Clearcasting.jpg",
    "Cultivation":"img/druid/Cultivation.jpg",
    "Cyclone":"img/druid/Cyclone.jpg",
    "Dash":"img/druid/Dash.jpg",
    "Earthwarden":"img/druid/Earthwarden.jpg",
    "Eclipse (Lunar)":"img/druid/Eclipse(Lunar).jpg",
    "Eclipse (Solar)":"img/druid/Eclipse(Solar).jpg",
    "Efflorescence":"img/druid/Efflorescence.jpg",
    "Entangling Roots":"img/druid/EntanglingRoots.jpg",
    "Feline Swiftness":"img/druid/FelineSwiftness.jpg",
    "Feral Affinity":"img/druid/FeralAffinity.jpg",
    "Feral Frenzy":"img/druid/FeralFrenzy.jpg",
    "Ferocious Bite":"img/druid/FerociousBite.jpg",
    "Flap":"img/druid/Flap.jpg",
    "Flourish":"img/druid/Flourish.jpg",
    "Force of Nature":"img/druid/ForceofNature.jpg",
    "Frenzied Regeneration":"img/druid/FrenziedRegeneration.jpg",
    "Fury of Elune":"img/druid/FuryofElune.jpg",
    "Galactic Guardian":"img/druid/GalacticGuardian.jpg",
    "Germination":"img/druid/Germination.jpg",
    "Gore":"img/druid/Gore.jpg",
    "Growl":"img/druid/Growl.jpg",
    "Guardian Affinity":"img/druid/GuardianAffinity.jpg",
    "Guardian of Elune":"img/druid/GuardianofElune.jpg",
    "Harmony":"img/druid/Harmony.jpg",
    "Heart of the Wild":"img/druid/HeartoftheWild.jpg",
    "Hibernate":"img/druid/Hibernate.jpg",
    "Incapacitating Roar":"img/druid/IncapacitatingRoar.jpg",
    "Incarnation: Guardian of Ursoc":"img/druid/IncarnationGuardianofUrsoc.jpg",
    "Incarnation: Chosen of Elune":"img/druid/IncarnationChosenofElune.jpg",
    "Incarnation: King of the Jungle":"img/druid/IncarnationKingoftheJungle.jpg",
    "Incarnation: Tree of Life":"img/druid/IncarnationTreeofLife.jpg",
    "Infected Wounds":"img/druid/InfectedWounds.jpg",
    "Inner Peace":"img/druid/InnerPeace.jpg",
    "Innervate":"img/druid/Innervate.jpg",
    "Ironbark":"img/druid/Ironbark.jpg",
    "Ironfur":"img/druid/Ironfur.jpg",
    "Lifebloom":"img/druid/Lifebloom.jpg",
    "Lunar Inspiration":"img/druid/LunarInspiration.jpg",
    "Maim":"img/druid/Maim.jpg",
    "Mangle":"img/druid/Mangle.jpg",
    "Mass Entanglement":"img/druid/MassEntanglement.jpg",
    "Maul":"img/druid/Maul.jpg",
    "Mighty Bash":"img/druid/MightyBash.jpg",
    "Moment of Clarity":"img/druid/MomentofClarity.jpg",
    "Nature's Balance":"img/druid/Nature'sBalance.jpg",
    "Nature's Cure":"img/druid/Nature'sCure.jpg",
    "Nature's Guardian":"img/druid/Nature'sGuardian.jpg",
    "Nature's Swiftness":"img/druid/Nature'sSwiftness.jpg",
    "New Moon":"img/druid/NewMoon.jpg",
    "Half Moon":"img/druid/HalfMoon.jpg",
    "Full Moon":"img/druid/FullMoon.jpg",
    "Nourish":"img/druid/Nourish.jpg",
    "Omen of Clarity":"img/druid/OmenofClarity.jpg",
    "Overgrowth":"img/druid/Overgrowth.jpg",
    "Photosynthesis":"img/druid/Photosynthesis.jpg",
    "Predator":"img/druid/Predator.jpg",
    "Predatory Swiftness":"img/druid/PredatorySwiftness.jpg",
    "Primal Wrath":"img/druid/PrimalWrath.jpg",
    "Prowl":"img/druid/Prowl.jpg",
    "Pulverize":"img/druid/Pulverize.jpg",
    "Rake":"img/druid/Rake.jpg",
    "Razor Claws":"img/druid/RazorClaws.jpg",
    "Rebirth":"img/druid/Rebirth.jpg",
    "Remove Corruption":"img/druid/RemoveCorruption.jpg",
    "Rend and Tear":"img/druid/RendandTear.jpg",
    "Renewal":"img/druid/Renewal.jpg",
    "Restoration Affinity":"img/druid/RestorationAffinity.jpg",
    "Revitalize":"img/druid/Revitalize.jpg",
    "Revive":"img/druid/Revive.jpg",
    "Rip":"img/druid/Rip.jpg",
    "Sabertooth":"img/druid/Sabertooth.jpg",
    "Savage Roar":"img/druid/SavageRoar.jpg",
    "Scent of Blood":"img/druid/ScentofBlood.jpg",
    "Shooting Stars":"img/druid/ShootingStars.jpg",
    "Shred":"img/druid/Shred.jpg",
    "Skull Bash":"img/druid/SkullBash.jpg",
    "Solar Beam":"img/druid/SolarBeam.jpg",
    "Solstice":"img/druid/Solstice.jpg",
    "Soothe":"img/druid/Soothe.jpg",
    "Soul of the Forest":"img/druid/SouloftheForest.jpg",
    "Spring Blossoms":"img/druid/SpringBlossoms.jpg",
    "Stampeding Roar":"img/druid/StampedingRoar.jpg",
    "Starfall":"img/druid/Starfall.jpg",
    "Starlord":"img/druid/Starlord.jpg",
    "Starsurge":"img/druid/Starsurge.jpg",
    "Stellar Drift":"img/druid/StellarDrift.jpg",
    "Stellar Flare":"img/druid/StellarFlare.jpg",
    "Survival Instincts":"img/druid/SurvivalInstincts.jpg",
    "Survival of the Fittest":"img/druid/SurvivaloftheFittest.jpg",
    "Swiftmend":"img/druid/Swiftmend.jpg",
    "Swipe":"img/druid/Swipe.jpg",
    "Thick Hide":"img/druid/ThickHide.jpg",
    "Thrash":"img/druid/Thrash.jpg",
    "Tiger Dash":"img/druid/TigerDash.jpg",
    "Tiger's Fury":"img/druid/Tiger'sFury.jpg",
    "Tooth and Claw":"img/druid/ToothandClaw.jpg",
    "Total Eclipse":"img/druid/.jpg",
    "Tranquility":"img/druid/Tranquility.jpg",
    "Travel Form":"img/druid/TravelForm.jpg",
    "Twin Moons":"img/druid/TwinMoons.jpg",
    "Typhoon":"img/druid/Typhoon.jpg",
    "Ursine Adept":"img/druid/UrsineAdept.jpg",
    "Ursol's Vortex":"img/druid/Ursol'sVortex.jpg",
    "Warrior of Elune":"img/druid/WarriorofElune.jpg",
    "Wild Charge":"img/druid/WildCharge.jpg",
    "Ysera's Gift":"img/druid/Ysera'sGift.jpg",

    //hunter
    "":"img/hunter/.jpg",
    "":"img/hunter/.jpg",
    "":"img/hunter/.jpg",
    "":"img/hunter/.jpg",
    "":"img/hunter/.jpg",
    "":"img/hunter/.jpg",
    "":"img/hunter/.jpg",
    "":"img/hunter/.jpg",
    "":"img/hunter/.jpg",
    "":"img/hunter/.jpg",
    "":"img/hunter/.jpg",
    "":"img/hunter/.jpg",
    "":"img/hunter/.jpg",
    "":"img/hunter/.jpg",
    "":"img/hunter/.jpg",
    "":"img/hunter/.jpg",


    //Mage
    "Arcane Blast":"img/mage/ArcaneBlast.jpg",
    "Arcane Barrage":"img/mage/ArcaneBarrage.jpg",


    //Monk
    "Vivify":"img/monk/Vivify.jpg",
    "Renewing Mist":"img/monk/RenewingMist.jpg",
    "Mana Tea":"img/monk/ManaTea.jpg",
    "Blackout Kick":"img/monk/BlackoutKick.jpg",
    "Chi-Ji":"img/monk/Chi-Ji.jpg", //???
    "Chi Burst":"img/monk/ChiBurst.jpg",
    "Detox":"img/monk/Detox.jpg",
    "Enveloping Breath":"img/monk/EnvelopingBreath.jpg",
    "Enveloping Mist":"img/monk/EnvelopingMist.jpg",
    "Essence Font":"img/monk/EssenceFont.jpg",
    "Expel Harm":"img/monk/ExpelHarm.jpg",
    "Fortifying Brew":"img/monk/FortifyingBrew2.jpg",
    "Gust of Mists":"img/monk/GustofMists.jpg",
    "Life Cocoon":"img/monk/LifeCocoon.jpg",
    "Provoke":"img/monk/Provoke.jpg",
    "Refreshing Jade Wind":"img/monk/RefreshingJadeWind.jpg",
    "Revival":"img/monk/Revival.jpg",
    "Rising Mist":"img/monk/RisingMist.jpg",
    "Rising Sun Kick":"img/monk/RisingSunKick.jpg",
    "Roll":"img/monk/Roll.jpg",
    "Soothing Mist":"img/monk/SoothingMist.jpg",
    "Spinning Crane Kick":"img/monk/SpinningCraneKick.jpg",
    "Thunder Focus Tea":"img/monk/ThunderFocusTea.jpg",
    "Tiger Palm":"img/monk/TigerPalm.jpg",
    "Tiger's Lust":"img/monk/TigersLust.jpg",
    "Touch Of Death":"img/monk/TouchOfDeath.jpg",
    "Yu'Lon":"img/monk/Yu'Lon.jpg",
    "Teachings of the Monastery":"img/monk/TeachingsOfTheMonastery.jpg",
    "Mystic Touch":"img/monk/MysticTouch.jpg",
    "Stagger":"img/monk/Stagger.jpg",
    "Light Stagger":"img/monk/LightStagger.jpg",
    "Moderate Stagger":"img/monk/ModerateStagger.jpg",
    "Heavy Stagger":"img/monk/HeavyStagger.jpg",
    "Breath Of Fire":"img/monk/BreathOfFire.jpg",
    "Celestial Brew":"img/monk/CelestialBrew.jpg",
    "Celestial Fortune":"img/monk/CelestialFortune.jpg",
    "Clash":"img/monk/Clash.jpg",
    "Gift Of The Ox":"img/monk/GiftOfTheOx.jpg",
    "Invoke Niuzao, the Black Ox":"img/monk/InvokeNiuzaotheBlackOx.jpg",
    "KegSmash":"img/monk/KegSmash.jpg",
    "Purifying Brew":"img/monk/PurifyingBrew.jpg",
    "Shuffle":"img/monk/Shuffle.jpg",
    "Spear Hand Strike":"img/monk/SpearHandStrike.jpg",
    "Zen Meditation":"img/monk/ZenMeditation.jpg",
    "Combo Strikes":"img/monk/ComboStrikes.jpg",
    "Disable":"img/monk/Disable.jpg",
    "Fists Of Fury":"img/monk/FistsOfFury.jpg",
    "Flying Serpent Kick":"img/monk/FlyingSerpentKick.jpg",
    "Invoke Xuen, the White Tiger":"img/monk/InvokeXuentheWhiteTiger.jpg",
    "Reawaken":"img/monk/Reawaken.jpg",
    "Storm, Earth And Fire":"img/monk/StormEarthAndFire.jpg",
    "Touch Of Karma":"img/monk/TouchOfKarma.jpg",
    "Windwalking":"img/monk/Windwalking.jpg",
    "Resuscitate":"img/monk/Resuscitate.jpg",
    "Chi Torpedo":"img/monk/ChiTorpedo.jpg",
    "Crackling Jade Lightning":"img/monk/CracklingJadeLightning.jpg",
    "Paralysis":"img/monk/Paralysis.jpg",
    "Transcendence":"img/monk/Transcendence.jpg",
    "Transcendence: Transfer":"img/monk/TranscendenceTransfer.jpg",
    "Focused Thunder":"img/monk/focusedThunder.jpg",
    "Chi of the Crane":"img/monk/chiofthecrane.jpg",
    "Summon Jade Serpent Statue":"img/monk/jadestatue.jpg",
    "Life Cycles":"img/monk/lifeCycles.jpg",
    "Mist Wrap":"img/monk/mistWrap.jpg",
    "Upwelling":"img/monk/upwelling.jpg",
    "Rushing Jade Wind":"img/monk/RefreshingJadeWind.jpg",
    "Good Karma":"img/monk/TouchOfKarma.jpg",
    "Ascension":"img/monk/Ascension.jpg",
    "Blackout Combo":"img/monk/BlackoutCombo.jpg",
    "Black Ox Brew":"img/monk/BlackOxBrew.jpg",
    "Bob and Weave":"img/monk/BobandWeave.jpg",
    "Celerity":"img/monk/Celerity.jpg",
    "Celestial Flames":"img/monk/CelestialFlames.jpg",
    "Dampen Harm":"img/monk/DampenHarm.jpg",
    "Diffuse Magic":"img/monk/DiffuseMagic.jpg",
    "Energizing Elixir":"img/monk/EnergizingElixir.jpg",
    "Exploding Keg":"img/monk/ExplodingKeg.jpg",
    "Eye of the Tiger":"img/monk/EyeoftheTiger.jpg",
    "Fist of the White Tiger":"img/monk/FistoftheWhiteTiger.jpg",
    "High Tolerance":"img/monk/HighTolerance.jpg",
    "Hit Combo":"img/monk/HitCombo.jpg",
    "Chi Wave":"img/monk/ChiWave.jpg",
    "Inner Strength":"img/monk/InnerStrength.jpg",
    "Light Brewing":"img/monk/LightBrewing.jpg",
    "Ring of Peace":"img/monk/RingofPeace.jpg",
    "Serenity":"img/monk/Serenity.jpg",
    "Song of Chi-Ji":"img/monk/SongofChi-Ji.jpg",
    "Special Delivery":"img/monk/SpecialDelivery.jpg",
    "Spirit of the Crane":"img/monk/SpiritoftheCrane.jpg",
    "Spiritual Focus":"img/monk/SpiritualFocus.jpg",
    "Spitfire":"img/monk/Spitfire.jpg",
    "Tiger Tail Sweep":"img/monk/TigerTailSweep.jpg",
    "Whirling Dragon Punch":"img/monk/WhirlingDragonPunch.jpg",

    //Rogue
    "Garrote":"img/rogue/Garrote.jpg",
    "Mutilate":"img/rogue/Mutilate.jpg",
    "Rupture":"img/rogue/Rupture.jpg",
    "Slice And Dice":"img/rogue/SliceAndDice.jpg",
    "Envenom":"img/rogue/Envenom.jpg",
    "Deadly Poison":"img/rogue/DeadlyPoison.jpg",

    //Shaman
    "Healing Surge":"img/shaman/HealingSurge.jpg",
    "Flame Shock":"img/shaman/FlameShock.jpg",
    "Lightning Bolt":"img/shaman/LightningBolt.jpg",
    "Lava Burst":"img/shaman/LavaBurst.jpg",
    "Healing Rain":"img/shaman/HealingRain.jpg",
    "Healing Tide Totem":"img/shaman/HealingTideTotem.jpg",
    "Ghost Wolf":"img/shaman/GhostWolf.jpg",
    "Riptide":"img/shaman/Riptide.jpg",
}