let iconsPath = {
    "Vivify":"img/mistweaver/Vivify.jpg",
    "Renewing Mist":"img/mistweaver/RenewingMist.jpg",
    "Mana Tea":"img/mistweaver/ManaTea.jpg",
    "Blackout Kick":"img/mistweaver/BlackoutKick.jpg",
    "Chi-Ji":"img/mistweaver/Chi-Ji.jpg", //???
    "Chi-JiActivate":"img/mistweaver/Chi-JiActivate.jpg", //?????
    "Chi Burst":"img/mistweaver/ChiBurst.jpg",
    "Detox":"img/mistweaver/Detox.jpg",
    "Enveloping Breath":"img/mistweaver/EnvelopingBreath.jpg",
    "Enveloping Mist":"img/mistweaver/EnvelopingMist.jpg",
    "Essence Font":"img/mistweaver/EssenceFont.jpg",
    "Expel Harm":"img/mistweaver/ExpelHarm.jpg",
    "Fortifying Brew":"img/mistweaver/FortifyingBrew.jpg",
    "Gust of Mists":"img/mistweaver/GustofMists.jpg",
    "Life Cocoon":"img/mistweaver/LifeCocoon.jpg",
    "Refreshing Jade Wind":"img/mistweaver/RefreshingJadeWind.jpg",
    "Revival":"img/mistweaver/Revival.jpg",
    "Rising Mist":"img/mistweaver/RisingMist.jpg",
    "Rising Sun Kick":"img/mistweaver/RisingSunKick.jpg",
    "Soothing Mist":"img/mistweaver/SoothingMist.jpg",
    "Spinning Crane Kick":"img/mistweaver/SpinningCraneKick.jpg",
    "Thunder Focus Tea":"img/mistweaver/ThunderFocusTea.jpg",
    "Tiger Palm":"img/mistweaver/TigerPalm.jpg",
    "Touch Of Death":"img/mistweaver/TouchOfDeath.jpg",
    "Yu'Lon":"img/mistweaver/Yu'Lon.jpg",
}