let specsName = {
    "mistweaver":"Mistweaver",
    "windwalker":"Windwalker",
    "brewmaster":"Brewmaster",
    "restorationShaman":"Restoration",
    "holyPriest":"Holy",
    "discPriest":"Discipline",
    "elemental":"Elemental",
    "assassination":"Assassination",
    "restorationDruid":"Restoration",
    "balance":"Balance",
    "arcane":"Arcane",
    "havoc":"Havoc",
    "fury":"Fury",
}
